# Generated by Django 5.2.6 on 2025-11-10 13:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('account_name', models.CharField(max_length=200, verbose_name='Account Name')),
                ('account_number', models.CharField(max_length=50, unique=True, verbose_name='Account Number')),
                ('account_type', models.CharField(choices=[('checking', 'Checking Account'), ('savings', 'Savings Account'), ('credit', 'Credit Card'), ('cash', 'Cash Account')], default='checking', max_length=20, verbose_name='Account Type')),
                ('bank_name', models.CharField(blank=True, max_length=200, verbose_name='Bank Name')),
                ('branch', models.CharField(blank=True, max_length=200, verbose_name='Branch')),
                ('currency', models.CharField(default='USD', max_length=10, verbose_name='Currency')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Opening Balance')),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Current Balance')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Accounts',
                'ordering': ['account_name'],
            },
        ),
        migrations.CreateModel(
            name='IncomingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('payment_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Payment Number')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name='Payment Date')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('check', 'Check'), ('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('online', 'Online Payment')], default='bank_transfer', max_length=20, verbose_name='Payment Method')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('received', 'Received'), ('cleared', 'Cleared'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Amount')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Reference')),
                ('check_number', models.CharField(blank=True, max_length=50, verbose_name='Check Number')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_payments', to='erp.bankaccount', verbose_name='Bank Account')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_payments', to='erp.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Incoming Payment',
                'verbose_name_plural': 'Incoming Payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncomingPaymentInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('amount_allocated', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Amount Allocated')),
                ('incoming_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='erp.incomingpayment', verbose_name='Incoming Payment')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_payments', to='erp.invoice', verbose_name='Invoice')),
            ],
            options={
                'verbose_name': 'Incoming Payment Invoice',
                'verbose_name_plural': 'Incoming Payment Invoices',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OutgoingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('payment_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Payment Number')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name='Payment Date')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('check', 'Check'), ('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('online', 'Online Payment')], default='bank_transfer', max_length=20, verbose_name='Payment Method')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('paid', 'Paid'), ('cleared', 'Cleared'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Amount')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Reference')),
                ('check_number', models.CharField(blank=True, max_length=50, verbose_name='Check Number')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_payments', to='erp.bankaccount', verbose_name='Bank Account')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_payments', to='erp.supplier', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Outgoing Payment',
                'verbose_name_plural': 'Outgoing Payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutgoingPaymentInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('amount_allocated', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Amount Allocated')),
                ('outgoing_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='erp.outgoingpayment', verbose_name='Outgoing Payment')),
                ('purchase_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_payments', to='erp.purchaseinvoice', verbose_name='Purchase Invoice')),
            ],
            options={
                'verbose_name': 'Outgoing Payment Invoice',
                'verbose_name_plural': 'Outgoing Payment Invoices',
                'ordering': ['id'],
            },
        ),
    ]
