# Generated by Django 6.0 on 2026-01-11 06:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsreceipt',
            name='purchase_order',
        ),
        migrations.RemoveField(
            model_name='goodsreceipt',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='goodsreceiptitem',
            name='received_quantity',
        ),
        migrations.AlterField(
            model_name='goodsreceipt',
            name='receipt_type',
            field=models.CharField(choices=[('opening', 'Opening Stock'), ('adjustment', 'Stock Adjustment'), ('found', 'Found/Recovered'), ('transfer', 'Transfer In'), ('other', 'Other')], default='opening', max_length=20, verbose_name='Receipt Type'),
        ),
        migrations.AlterField(
            model_name='goodsreceipt',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='goodsreceipt',
            name='stock_updated',
            field=models.BooleanField(default=False, editable=False, verbose_name='Stock Updated'),
        ),
        migrations.AlterField(
            model_name='goodsreceipt',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='erp.warehouse', verbose_name='Warehouse'),
        ),
        migrations.AlterField(
            model_name='goodsreceiptitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Quantity'),
        ),
        migrations.CreateModel(
            name='GoodsReceiptPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('receipt_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Receipt Number')),
                ('receipt_date', models.DateField(default=django.utils.timezone.now, verbose_name='Receipt Date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('partial', 'Partially Received'), ('received', 'Received'), ('inspected', 'Inspected'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='draft', max_length=20, verbose_name='Status')),
                ('received_by', models.CharField(blank=True, max_length=100, verbose_name='Received By')),
                ('inspected_by', models.CharField(blank=True, max_length=100, verbose_name='Inspected By')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Reference')),
                ('supplier_delivery_note', models.CharField(blank=True, max_length=100, verbose_name='Supplier Delivery Note')),
                ('stock_updated', models.BooleanField(default=False, editable=False, verbose_name='Stock Updated')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts_po', to='erp.purchaseorder', verbose_name='Purchase Order')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts_po', to='erp.supplier', verbose_name='Supplier')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts_po', to='erp.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Goods Receipt (PO)',
                'verbose_name_plural': 'Goods Receipts (PO)',
                'ordering': ['-receipt_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptPOItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('ordered_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10, verbose_name='Ordered Qty')),
                ('received_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Received Qty')),
                ('rejected_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Rejected Qty')),
                ('accepted_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10, verbose_name='Accepted Qty')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Unit Price')),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Line Total')),
                ('rejection_reason', models.CharField(blank=True, max_length=200, verbose_name='Rejection Reason')),
                ('goods_receipt_po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp.goodsreceiptpo', verbose_name='Goods Receipt PO')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Goods Receipt PO Item',
                'verbose_name_plural': 'Goods Receipt PO Items',
                'ordering': ['id'],
            },
        ),
    ]
