# Generated by Django 6.0 on 2026-01-04 03:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_accounttype_fiscalyear_chartofaccounts_costcenter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('code', models.CharField(help_text='ISO 4217 code (e.g., USD, BDT, EUR)', max_length=3, unique=True, verbose_name='Currency Code')),
                ('name', models.CharField(max_length=100, verbose_name='Currency Name')),
                ('symbol', models.CharField(help_text='e.g., $, ৳, €', max_length=10, verbose_name='Symbol')),
                ('decimal_places', models.PositiveSmallIntegerField(default=2, verbose_name='Decimal Places')),
                ('is_base_currency', models.BooleanField(default=False, help_text='Only one currency can be base', verbose_name='Base Currency')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'ordering': ['-is_base_currency', 'code'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Term Name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Term Code')),
                ('days', models.PositiveIntegerField(default=0, help_text='Number of days for payment', verbose_name='Days')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('discount_days', models.PositiveIntegerField(default=0, help_text='Days within which discount applies', verbose_name='Discount Days')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Discount (%)')),
            ],
            options={
                'verbose_name': 'Payment Term',
                'verbose_name_plural': 'Payment Terms',
                'ordering': ['days', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Unit Name')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Unit Code')),
                ('uom_type', models.CharField(choices=[('unit', 'Unit'), ('weight', 'Weight'), ('volume', 'Volume'), ('length', 'Length'), ('area', 'Area'), ('time', 'Time')], default='unit', max_length=20, verbose_name='Type')),
                ('is_base_unit', models.BooleanField(default=False, help_text='Base unit for this type', verbose_name='Base Unit')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Unit of Measure',
                'verbose_name_plural': 'Units of Measure',
                'ordering': ['uom_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Price List Name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Price List Code')),
                ('price_type', models.CharField(choices=[('sales', 'Sales Price'), ('purchase', 'Purchase Price')], default='sales', max_length=20, verbose_name='Price Type')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('valid_from', models.DateField(default=django.utils.timezone.now, verbose_name='Valid From')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Valid To')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='price_lists', to='erp.currency', verbose_name='Currency')),
            ],
            options={
                'verbose_name': 'Price List',
                'verbose_name_plural': 'Price Lists',
                'ordering': ['price_type', '-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TaxType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tax Name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Tax Code')),
                ('category', models.CharField(choices=[('sales', 'Sales Tax'), ('purchase', 'Purchase Tax'), ('both', 'Both Sales & Purchase')], default='both', max_length=20, verbose_name='Category')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('purchase_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_tax_types', to='erp.chartofaccounts', verbose_name='Purchase Tax Account')),
                ('sales_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_tax_types', to='erp.chartofaccounts', verbose_name='Sales Tax Account')),
            ],
            options={
                'verbose_name': 'Tax Type',
                'verbose_name_plural': 'Tax Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(help_text='e.g., Standard Rate, Reduced Rate', max_length=100, verbose_name='Rate Name')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Rate (%)')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default Rate')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('effective_from', models.DateField(default=django.utils.timezone.now, verbose_name='Effective From')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='Effective To')),
                ('tax_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rates', to='erp.taxtype', verbose_name='Tax Type')),
            ],
            options={
                'verbose_name': 'Tax Rate',
                'verbose_name_plural': 'Tax Rates',
                'ordering': ['tax_type', '-is_default', 'rate'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='Exchange Rate')),
                ('effective_date', models.DateField(default=django.utils.timezone.now, verbose_name='Effective Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rates_from', to='erp.currency', verbose_name='From Currency')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rates_to', to='erp.currency', verbose_name='To Currency')),
            ],
            options={
                'verbose_name': 'Exchange Rate',
                'verbose_name_plural': 'Exchange Rates',
                'ordering': ['-effective_date', 'from_currency'],
                'unique_together': {('from_currency', 'to_currency', 'effective_date')},
            },
        ),
        migrations.CreateModel(
            name='PriceListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Unit Price')),
                ('min_quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Minimum quantity for this price', max_digits=10, verbose_name='Minimum Quantity')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Discount (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp.pricelist', verbose_name='Price List')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_list_items', to='erp.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Price List Item',
                'verbose_name_plural': 'Price List Items',
                'ordering': ['price_list', 'product', 'min_quantity'],
                'unique_together': {('price_list', 'product', 'min_quantity')},
            },
        ),
        migrations.CreateModel(
            name='UOMConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('conversion_factor', models.DecimalField(decimal_places=6, help_text='1 From UOM = X To UOM', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='Conversion Factor')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('from_uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversions_from', to='erp.unitofmeasure', verbose_name='From UOM')),
                ('to_uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversions_to', to='erp.unitofmeasure', verbose_name='To UOM')),
            ],
            options={
                'verbose_name': 'UOM Conversion',
                'verbose_name_plural': 'UOM Conversions',
                'ordering': ['from_uom', 'to_uom'],
                'unique_together': {('from_uom', 'to_uom')},
            },
        ),
    ]
