"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _


def admin_changelist(app_label, model_name):
    """Helper function to generate admin changelist URL"""
    return lambda request: reverse_lazy(f"admin:{app_label}_{model_name}_changelist")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9ndkcy2!xmq^31o+t#+6#p8wn%#_$khp#%*zoe+&0xj32^_+am'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'unfold.contrib.import_export',
    'unfold.contrib.guardian',
    'unfold.contrib.simple_history',
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Local apps
    'erp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'erp.context_processors.company_info',  # Add company info to all templates
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Unfold Admin Configuration
UNFOLD = {
    "SITE_TITLE": "ERP Admin Panel",
    "SITE_HEADER": "ERP Administration",
    "SITE_URL": "/",
    "SITE_SYMBOL": "speed",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "ENVIRONMENT": "config.settings.environment_callback",
    "COLORS": {
        "primary": {
            "50": "252 254 235",   # Very light lime
            "100": "247 252 213",  # Light lime
            "200": "238 248 178",  # Lighter lime
            "300": "226 242 142",  # Light lime green
            "400": "208 234 106",  # Medium lime
            "500": "196 216 46",   # Main lime color (#c4d82e)
            "600": "168 184 42",   # Darker lime
            "700": "140 154 35",   # Dark lime
            "800": "112 123 28",   # Darker
            "900": "84 92 21",     # Very dark lime
            "950": "56 61 14",     # Darkest lime
        },
    },
    "STYLES": [
        lambda request: static("admin/css/custom_sidebar.css"),
        lambda request: static("admin/css/custom_tabs.css"),
    ],
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": _("Dashboard"),
                "separator": True,
                "items": [
                    {
                        "title": _("Dashboard"),
                        "icon": "dashboard",
                        "link": lambda request: reverse_lazy("erp:dashboard"),
                    },
                ],
            },
            {
                "title": _("Sales Management"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Customers"),
                        "icon": "people",
                        "link": admin_changelist("erp", "customer"),
                        "permission": lambda request: request.user.has_perm("erp.view_customer"),
                    },
                    {
                        "title": _("Sales Persons"),
                        "icon": "badge",
                        "link": admin_changelist("erp", "salesperson"),
                        "permission": lambda request: request.user.has_perm("erp.view_salesperson"),
                    },
                    {
                        "title": _("Sales Quotations"),
                        "icon": "request_quote",
                        "link": admin_changelist("erp", "salesquotation"),
                        "permission": lambda request: request.user.has_perm("erp.view_salesquotation"),
                    },
                    {
                        "title": _("Sales Orders"),
                        "icon": "shopping_cart",
                        "link": admin_changelist("erp", "salesorder"),
                        "permission": lambda request: request.user.has_perm("erp.view_salesorder"),
                    },
                    {
                        "title": _("Deliveries"),
                        "icon": "local_shipping",
                        "link": admin_changelist("erp", "delivery"),
                        "permission": lambda request: request.user.has_perm("erp.view_delivery"),
                    },
                    {
                        "title": _("Invoices"),
                        "icon": "receipt",
                        "link": admin_changelist("erp", "invoice"),
                        "permission": lambda request: request.user.has_perm("erp.view_invoice"),
                    },
                    {
                        "title": _("Sales Returns"),
                        "icon": "assignment_return",
                        "link": admin_changelist("erp", "salesreturn"),
                        "permission": lambda request: request.user.has_perm("erp.view_salesreturn"),
                    },
                ],
            },
            {
                "title": _("Purchase Management"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Suppliers"),
                        "icon": "local_shipping",
                        "link": admin_changelist("erp", "supplier"),
                        "permission": lambda request: request.user.has_perm("erp.view_supplier"),
                    },
                    {
                        "title": _("Purchase Quotations"),
                        "icon": "request_quote",
                        "link": admin_changelist("erp", "purchasequotation"),
                        "permission": lambda request: request.user.has_perm("erp.view_purchasequotation"),
                    },
                    {
                        "title": _("Purchase Orders"),
                        "icon": "shopping_bag",
                        "link": admin_changelist("erp", "purchaseorder"),
                        "permission": lambda request: request.user.has_perm("erp.view_purchaseorder"),
                    },
                    {
                        "title": _("Purchase Invoices"),
                        "icon": "receipt_long",
                        "link": admin_changelist("erp", "purchaseinvoice"),
                        "permission": lambda request: request.user.has_perm("erp.view_purchaseinvoice"),
                    },
                    {
                        "title": _("Purchase Returns"),
                        "icon": "keyboard_return",
                        "link": admin_changelist("erp", "purchasereturn"),
                        "permission": lambda request: request.user.has_perm("erp.view_purchasereturn"),
                    },
                ],
            },
            {
                "title": _("Production Management"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Bill of Materials"),
                        "icon": "list_alt",
                        "link": admin_changelist("erp", "billofmaterials"),
                        "permission": lambda request: request.user.has_perm("erp.view_billofmaterials"),
                    },
                    {
                        "title": _("Production Orders"),
                        "icon": "precision_manufacturing",
                        "link": admin_changelist("erp", "productionorder"),
                        "permission": lambda request: request.user.has_perm("erp.view_productionorder"),
                    },
                    {
                        "title": _("Production Receipts"),
                        "icon": "fact_check",
                        "link": admin_changelist("erp", "productionreceipt"),
                        "permission": lambda request: request.user.has_perm("erp.view_productionreceipt"),
                    },
                ],
            },
            {
                "title": _("Inventory Management"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Warehouses"),
                        "icon": "warehouse",
                        "link": admin_changelist("erp", "warehouse"),
                        "permission": lambda request: request.user.has_perm("erp.view_warehouse"),
                    },
                    {
                        "title": _("Categories"),
                        "icon": "category",
                        "link": admin_changelist("erp", "category"),
                        "permission": lambda request: request.user.has_perm("erp.view_category"),
                    },
                    {
                        "title": _("Products"),
                        "icon": "inventory_2",
                        "link": admin_changelist("erp", "product"),
                        "permission": lambda request: request.user.has_perm("erp.view_product"),
                    },
                    {
                        "title": _("Goods Receipts"),
                        "icon": "move_to_inbox",
                        "link": admin_changelist("erp", "goodsreceipt"),
                        "permission": lambda request: request.user.has_perm("erp.view_goodsreceipt"),
                    },
                    {
                        "title": _("Goods Issues"),
                        "icon": "outbox",
                        "link": admin_changelist("erp", "goodsissue"),
                        "permission": lambda request: request.user.has_perm("erp.view_goodsissue"),
                    },
                    {
                        "title": _("Inventory Transfers"),
                        "icon": "compare_arrows",
                        "link": admin_changelist("erp", "inventorytransfer"),
                        "permission": lambda request: request.user.has_perm("erp.view_inventorytransfer"),
                    },
                    {
                        "title": _("Warehouse Stock"),
                        "icon": "storage",
                        "link": admin_changelist("erp", "productwarehousestock"),
                        "permission": lambda request: request.user.has_perm("erp.view_productwarehousestock"),
                    },
                    {
                        "title": _("Stock Transactions"),
                        "icon": "swap_horiz",
                        "link": admin_changelist("erp", "stocktransaction"),
                        "permission": lambda request: request.user.has_perm("erp.view_stocktransaction"),
                    },
                ],
            },
            {
                "title": _("Banking & Payments"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Bank Accounts"),
                        "icon": "account_balance",
                        "link": admin_changelist("erp", "bankaccount"),
                        "permission": lambda request: request.user.has_perm("erp.view_bankaccount"),
                    },
                    {
                        "title": _("Incoming Payments"),
                        "icon": "arrow_downward",
                        "link": admin_changelist("erp", "incomingpayment"),
                        "permission": lambda request: request.user.has_perm("erp.view_incomingpayment"),
                    },
                    {
                        "title": _("Outgoing Payments"),
                        "icon": "arrow_upward",
                        "link": admin_changelist("erp", "outgoingpayment"),
                        "permission": lambda request: request.user.has_perm("erp.view_outgoingpayment"),
                    },
                ],
            },
            {
                "title": _("Accounting & Finance"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Chart of Accounts"),
                        "icon": "account_tree",
                        "link": admin_changelist("erp", "chartofaccounts"),
                        "permission": lambda request: request.user.has_perm("erp.view_chartofaccounts"),
                    },
                    {
                        "title": _("Account Types"),
                        "icon": "category",
                        "link": admin_changelist("erp", "accounttype"),
                        "permission": lambda request: request.user.has_perm("erp.view_accounttype"),
                    },
                    {
                        "title": _("Journal Entries"),
                        "icon": "book",
                        "link": admin_changelist("erp", "journalentry"),
                        "permission": lambda request: request.user.has_perm("erp.view_journalentry"),
                    },
                    {
                        "title": _("Projects"),
                        "icon": "work",
                        "link": admin_changelist("erp", "project"),
                        "permission": lambda request: request.user.has_perm("erp.view_project"),
                    },
                    {
                        "title": _("Cost Centers"),
                        "icon": "business_center",
                        "link": admin_changelist("erp", "costcenter"),
                        "permission": lambda request: request.user.has_perm("erp.view_costcenter"),
                    },
                    {
                        "title": _("Fiscal Years"),
                        "icon": "calendar_today",
                        "link": admin_changelist("erp", "fiscalyear"),
                        "permission": lambda request: request.user.has_perm("erp.view_fiscalyear"),
                    },
                    {
                        "title": _("Budgets"),
                        "icon": "pie_chart",
                        "link": admin_changelist("erp", "budget"),
                        "permission": lambda request: request.user.has_perm("erp.view_budget"),
                    },
                ],
            },
            {
                "title": _("Reports"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Sales Report"),
                        "icon": "assessment",
                        "link": lambda request: reverse_lazy("erp:sales-report"),
                    },
                    {
                        "title": _("Purchase Report"),
                        "icon": "summarize",
                        "link": lambda request: reverse_lazy("erp:purchase-report"),
                    },
                    {
                        "title": _("Stock Report"),
                        "icon": "inventory",
                        "link": lambda request: reverse_lazy("erp:stock-report"),
                    },
                ],
            },
            {
                "title": _("Settings"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Company"),
                        "icon": "business",
                        "link": admin_changelist("erp", "company"),
                        "permission": lambda request: request.user.has_perm("erp.view_company"),
                    },
                ],
            },
            {
                "title": _("Authentication & Authorization"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Users"),
                        "icon": "person",
                        "link": lambda request: reverse_lazy("admin:auth_user_changelist"),
                    },
                    {
                        "title": _("Groups"),
                        "icon": "group",
                        "link": lambda request: reverse_lazy("admin:auth_group_changelist"),
                    },
                ],
            },
        ],
    },
}


def environment_callback(request):
    """
    Callback to show environment badge in admin
    """
    return ["Development", "warning"]
